I don't even remember.  These changes were made a while ago.  Between my changes and upstream changes, I'm sure everything's broken right now.

diff --git a/ait b/ait
--- a/ait
+++ b/ait
@@ -9,7 +9,7 @@
 # expand_aliases makes aliases work.  It's not set in scripts by default.
 shopt -s expand_aliases
 
-source device.conf
+source $configuration_file
 
 start_time="$(date "+%Y-%m-%d_%H:%M:%S")"
 
@@ -649,11 +649,11 @@ cookies='cookies.txt'
 cookie_url='https://google.com'
 ack_url='https://developers.google.com/profile/acknowledgeNotification'
 xsrf_token=$(xsrf_token)
-latest_listing=$(latest_listing)
-latest_image_link=$(latest_image_link)
-image_file=$(echo "${latest_image_link}" | sed 's/^.*\///')
-image_dir=$(echo "${image_file}"| sed 's/-factory-[a-z0-9]*\.zip$//')
-system_image_dir="${image_dir}_system"
+#latest_listing=$(latest_listing)
+#latest_image_link=$(latest_image_link)
+#image_file=$(echo "${latest_image_link}" | sed 's/^.*\///')
+#image_dir=$(echo "${image_file}"| sed 's/-factory-[a-z0-9]*\.zip$//')
+#system_image_dir="${image_dir}_system"
 latest_twrp_image_link=$(latest_twrp_image_link)
 twrp_image_file=$(echo "${latest_twrp_image_link}" | sed 's/^.*\///')
 magisk_file="Magisk.zip"
@@ -662,23 +662,23 @@ superuser_file='superuser.zip'
 
 
 # TODO:  This logic does not belong here.
-start_version=$(adb shell getprop ro.build.version.release)
-start_major_version=$(echo "${start_version}" | sed 's/\..*//g')
-echo "${start_major_version}" | grep -q '^[0-9]$' || {
-  error_output "Invalid starting version:  ${start_major_version}"
-  #exit 1
-}
-latest_version=$(latest_image_version)
-latest_major_version=$(echo "${latest_version}" | sed 's/\..*//g')
-echo "${latest_major_version}" | grep -q '^[0-9]$'|| {
-  error_output "Invalid latest version:  ${latest_major_version}"
-  exit 1
-}
+#start_version=$(adb shell getprop ro.build.version.release)
+#start_major_version=$(echo "${start_version}" | sed 's/\..*//g')
+#echo "${start_major_version}" | grep -q '^[0-9]$' || {
+#  error_output "Invalid starting version:  ${start_major_version}"
+#  #exit 1
+#}
+#latest_version=$(latest_image_version)
+#latest_major_version=$(echo "${latest_version}" | sed 's/\..*//g')
+#echo "${latest_major_version}" | grep -q '^[0-9]$'|| {
+#  error_output "Invalid latest version:  ${latest_major_version}"
+#  exit 1
+#}
 
-! test "${start_version}" =  "${latest_version}" || {
-  prompt "WARNING:  Latest image is the same version already on the device.  Continue?  [Y,n]  "
-  echo "${response}" | grep -iv 'n' || exit 1
-}
+#! test "${start_version}" =  "${latest_version}" || {
+#  prompt "WARNING:  Latest image is the same version already on the device.  Continue?  [Y,n]  "
+#  echo "${response}" | grep -iv 'n' || exit 1
+#}
 
 # TODO:  This does not belong here either.
 cycle_adb || {
@@ -692,10 +692,10 @@ start_adb_count=$(count_adb_devices)
 start_fastboot_count=$(count_fastboot_devices)
 start_device_count=$(( start_adb_count + start_fastboot_count ))
 
-mkdir -p ${backup_dir} || {
-  error_output "Failed to create backup directory:  ${backup_dir}"
-  exit 1
-}
+#mkdir -p ${backup_dir} || {
+#  error_output "Failed to create backup directory:  ${backup_dir}"
+#  exit 1
+#}
 
 cd $work_dir || {
   error_output "Failed to enter directory:  /tmp"
diff --git a/upgrade_nexus b/upgrade_nexus
--- a/upgrade_nexus
+++ b/upgrade_nexus
@@ -6,23 +6,26 @@
 # published by Sam Hocevar. See WTFPL.txt or http://www.wtfpl.net/ for more
 # details.
 
+if test $# -lt 1; then
+  echo Specify a configuration file. >&2
+  exit 1
+fi
+configuration_file="${1}"
 source ait
 
 function main {
   test 1 -eq $start_device_count        || fail "I expect one device, but found ${start_device_count} (${start_adb_count} adb and ${start_fastboot_count} fastboot)."
-  backup_data                           || fail "Failed to backup data."
-  download_latest_stock_image           || fail "Failed to download stock image."
-  download_latest_twrp_image            || fail "Failed to download TWRP recovery image."
-  download_magisk                       || fail "Failed to download Magisk."
-  download_superuser                    || fail "Failed to download superuser."
-  unpack_image                          || fail "Failed to unpack image."
-  install_image                         || fail "Failed to install image."
+  #backup_data                           || fail "Failed to backup data."
+  #download_latest_stock_image           || fail "Failed to download stock image."
+  #download_latest_twrp_image            || fail "Failed to download TWRP recovery image."
+  #download_superuser                    || fail "Failed to download superuser."
+  #unpack_image                          || fail "Failed to unpack image."
+  #install_image                         || fail "Failed to install image."
   install_twrp_image                    || fail "Failed to install TWRP recovery image."
-  install_magisk                        || fail "Failed to install Magisk."
   install_superuser                     || fail "Failed to install superuser."
   # Leave fastboot.
   reboot_from_device_to_device          || fail "Failed to reboot from adb to adb."
-  restore_data                          || fail "Failed to restore application data."
+  #restore_data                          || fail "Failed to restore application data."
   output                                "Success!"
 }
 
